// <auto-generated />
using System;
using AkinTestEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AkinTestEF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220524123117_added data to Author class")]
    partial class addeddatatoAuthorclass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AkinTestEF.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BookId = 0,
                            Name = "Marcel",
                            SurName = "Proust"
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 0,
                            Name = "James",
                            SurName = "Joyce"
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 0,
                            Name = "Miguel",
                            SurName = "Cervantes"
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 0,
                            Name = "Gabriel Garcia",
                            SurName = "Marquez"
                        });
                });

            modelBuilder.Entity("AkinTestEF.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Published")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("BookId");

                    b.HasIndex("StudentId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Published = new DateTime(1913, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            Title = " In Search of Lost Time"
                        },
                        new
                        {
                            BookId = 2,
                            Published = new DateTime(1904, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 1,
                            Title = "Ulysses"
                        },
                        new
                        {
                            BookId = 3,
                            Published = new DateTime(1605, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 2,
                            Title = " Don Quixote"
                        },
                        new
                        {
                            BookId = 4,
                            Published = new DateTime(1967, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = 3,
                            Title = " One Hundred Years of Solitude"
                        });
                });

            modelBuilder.Entity("AkinTestEF.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Akin",
                            LastName = "Ozkan"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Sagar",
                            LastName = "Bhanadari"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Fatih",
                            LastName = "Ozer"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Florian",
                            LastName = "Esprit"
                        });
                });

            modelBuilder.Entity("AkinTestEF.Models.Book", b =>
                {
                    b.HasOne("AkinTestEF.Models.Student", "Student")
                        .WithMany("Books")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
